name: Punjabi Class Registration Form
description: Registration form for Sterling Heights Gurdwara Punjabi class
author: Gulshan Singh gsingh2011@gmail.com
homepage: http://gulshansingh.com
version: "1.0.0"
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  sprintf: '>=1.0.8 <2.0.0'
  polymer: '>=0.12.0 <0.13.0'
  form_elements:
    path: /mnt/ubuntu/home/gulshan/code/dart/form_elements
transformers:
- polymer:
    entry_points: web/index.html
